name: 'Prerelease Number Generator'
description: 'Generate sequential prerelease numbers for prefix and prerelease type'
author: 'Dmitry Khlybov'
runs:
  using: 'node12'
  main: 'main.js'
inputs:
  token:
    description: 'GitHub Token to create and delete refs (GITHUB_TOKEN)'
    required: false # Not required when getting the stored number for later jobs, only in the first jobs when it's generated
  prefix:
    description: 'Prefix (master, dev, v1, 1.0, 1.0.0, etc...) which is scope where prerelease numbers are sequential and unique inside'
    required: true
  prerelease_type:
    description: 'Prerelease type (alpha, betta, preview, cr, etc...) which is scope where prerelease numbers are sequential and unique inside'
    required: true

outputs:
  prerelease_number:
    description: 'Generated prerelease number (master-alpha-1, master-alpha-2, dev-beta-1, 1.0.0-cr-3, etc...)'

branding:
  icon: 'hash'
  color: 'green'
